### ISSUE TITLE
Property does not override any property from its superclass

### ISSUE THREAD

**Issue by iperfectapp** [RainwayApp/flutter_home_indicator#1]
![image](https://user-images.githubusercontent.com/3021764/67485862-7b461680-f69d-11e9-8a1b-7ad60d442c37.png)

I can not run code correct,Do you know the reason?Thanks for your contribution！

**Comment by iperfectapp** [comment]
After I remove 'override' ,it can run. But in iOS13, the sdk has no effect.

**Comment by lynn** [comment]
Hi, thanks for your report!

I struggled with the syntax here a little too while I was building the library. I think it has to do with different Swift versions requiring different syntaxes for properties.

In Swift version 4.2, which the product we made this for uses, this syntax seems to be valid. But in other versions, Swift expects:

```swift
override func prefersHomeIndicatorAutoHidden() -> Bool {
  ...
}
```

…overriding `prefersHomeIndicatorAutoHidden` as a function and not a property.

Try adding this to the bottom of your project's `Podfile`:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'   # <-- add this line
    end
  end
end
```

`'4.0'` would probably also work (not sure).

I'm actually not a Swift (or Objective-C) programmer at all, so I don't know the proper way to deal with this issue. Maybe if I figure out which version the syntax changed in, I can use `#if swift(>=x.y)` to support both versions.

I found [this](https://stackoverflow.com/questions/38862208/preferredstatusbarstyle-removed-in-swift-3), which seems to say it was Swift 3.0 that introduced the syntax change. But all versions of Swift supported by Flutter are ≥ 3.0, so I'm not sure what the deal is. 🙁

**Comment by lynn** [comment]
> After I remove 'override' ,it can run. But in iOS13, the sdk has no effect.

I assume that if you remove `override`, then the default behavior (= "never hide the home indicator") will, well, not get overridden. The code might compile, but it's probably just shadowing the thing it should be replacing in the super-super-class.

**Comment by lynn** [comment]
I changed the code to have: `#if swift(>=4.2)` (one syntax) `#else` (other syntax) `#endif`.

This is pushed as 1.1.3, and I can compile it with both `config.build_settings['SWIFT_VERSION'] = '4.1'` and `config.build_settings['SWIFT_VERSION'] = '4.2'` now, so I think the issue might be fixed 🙂.

Can you update to 1.1.3 and verify, @iperfectapp?

**Comment by iperfectapp** [comment]
I update to 1.1.3,it fix my problem，thanks very much!!! I am in China, Can I buy your coffee?

**Comment by andrewmd5** [comment]
Hi @iperfectapp -- we're not big coffee drinkers, though if you'd like to support our work I'd ask you donate to a charity on our behalf. One near and dear to my heart is [CRY UK](https://www.c-r-y.org.uk/) who could use support.

**Comment by iperfectapp** [comment]
Thanks very much
