### ISSUE TITLE
The plugin `home_indicator` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by rafagan** [RainwayApp/flutter_home_indicator#11]
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

Any Help to solve that issue?

**Comment by nohli** [comment]
https://github.com/RainwayApp/flutter_home_indicator/issues/9#issuecomment-963206779
