### ISSUE TITLE
update kotlin version in android/build.gradle

### ISSUE THREAD

**Issue by nohli** [RainwayApp/flutter_home_indicator#2]
Ironically, this works like a charm on iOS, but broke my apk build:

> ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':home_indicator' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
> 

(my gradle plugin is not the latest, but from april)

If you replace
`
ext.kotlin_version = '1.2.71'
`
with
`
ext.kotlin_version = '1.3.50'
`

it works - at least for me.

**Comment by stx** [comment]
Same here. Could use the same fix because Gradle 3.3.1 is needed for other plugins, and that requires Kotlin Gradle 1.3 minimum.

**Comment by lynn** [comment]
Thanks for catching this! We don't target Android yet, so it slipped under the radar.

I applied the Kotlin version change. Please upgrade to version 1.1.4.
