### ISSUE TITLE
'home_indicator/home_indicator-Swift.h' file not found

### ISSUE THREAD

**Issue by iperfectapp** [RainwayApp/flutter_home_indicator#3]
I create a flutter project, iOS use Objective-C language, It does not work.

![image](https://user-images.githubusercontent.com/3021764/68490457-f30e6680-0283-11ea-83ee-88f6b1d3ff06.png)

**Comment by soska12** [comment]
This is the same for me, its not working with an ObjC project :(

**Comment by soska12** [comment]
According to this: 
https://github.com/flutter/flutter/issues/16049

> Objective-C apps still cannot use Swift plugins as libraries (Podfile does not contain use_frameworks!), which is the default for a newly created Objective-C Flutter project. I'm going to use this issue to track these outstanding issues.

**Comment by iperfectapp** [comment]
@soska12 @lynn @Codeusa Thanks very much

**Comment by changeforyouself** [comment]
//#import <home_indicator/home_indicator-Swift.h>
#if __has_include(<home_indicator/home_indicator-Swift.h>)
#import <home_indicator/home_indicator-Swift.h>
#else
// Support project import fallback if the generated compatibility header
// is not copied when this plugin is created as a library.
// https://forums.swift.org/t/swift-static-libraries-dont-copy-generated-objective-c-header/19816
#import "home_indicator-Swift.h"
#endif

this will be ok
