### ISSUE TITLE
I can't use this plugin

### ISSUE THREAD

**Issue by wwtssu** [RainwayApp/flutter_home_indicator#4]
I have some problem
when I use "pod install",it's show
<img width="565" alt="464E78518C5B966F2EE5A1C1CA362034" src="https://user-images.githubusercontent.com/57695674/75863540-9e4ab900-5e3b-11ea-9512-bd89905058af.png">
so I add "SWIFT_VERSION" in my target and run "pod install", it's like it
![4811E677D18484C26D5B10F10F6EE849](https://user-images.githubusercontent.com/57695674/75863552-a4d93080-5e3b-11ea-84eb-664560c2e27e.jpg)
I don't know how to solve the problem
what should I do? help me! Thanks

**Comment by joasag** [comment]
I have the same issue!

**Comment by cristian1980** [comment]
I replaced:
`#import` <home_indicator/home_indicator-Swift.h>
with:
`#import` <home_indicator-Swift.h>
and it seems to be working. That line needs to be changed inside this project or it will be overwritten on every pull.

**Comment by cristian1980** [comment]
Another fix is adding use_frameworks! to Podfile
