### ISSUE TITLE
Migration to Android V2 embedding

### ISSUE THREAD

**Issue by volgin** [RainwayApp/flutter_home_indicator#9]
I get the following warning during my builds:

```
The plugin `home_indicator` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

**Comment by nohli** [comment]
FYI If you always want to hide the home indicator, you don't necessarily need this package any more, you could use:
```
  SystemChrome.setEnabledSystemUIMode(
    SystemUiMode.leanBack,
  );
```
or without hiding the status bar:
```
  SystemChrome.setEnabledSystemUIMode(
    SystemUiMode.manual,
    overlays: <SystemUiOverlay>[SystemUiOverlay.top],
  );
```

Note that this also hides system UI on Android (like software navigation buttons), so using `flutter_home_indicator` is still preferred if only hiding the home button.

https://api.flutter.dev/flutter/services/SystemUiMode.html

**Comment by Daniel-BD** [comment]
While this is true, you still can't "defer edges" in Flutter itself. What I mean is that there's not way to do  `HomeIndicator.deferScreenEdges([ScreenEdge.bottom]);` in Flutter at the moment. Doing this modifies the [preferredScreenEdgesDeferringSystemGestures](https://developer.apple.com/documentation/uikit/uiviewcontroller/2887512-preferredscreenedgesdeferringsys) property on iOS. As far as I can tell, this is not exposed in Flutter (I've searched the Flutter/Flutter repo for preferredScreenEdgesDeferringSystemGestures and got no hits, as opposed to in this packages repo)

> FYI If you always want to hide the home indicator, you don't need this package any more, just use:
> 
> ```
>   SystemChrome.setEnabledSystemUIMode(
>     SystemUiMode.immersive,
>     overlays: <SystemUiOverlay>[],
>   );
> ```

**Comment by nohli** [comment]
Opened a [PR](https://github.com/RainwayApp/flutter_home_indicator/pull/10). In the meantime, you could ignore the warning, or use:

```
  home_indicator:
    git:
      url: https://github.com/nohli/flutter_home_indicator.git
      ref: migrate-to-android-v2-embedding
```

**Comment by RyuNen344** [comment]
any updates....?

**Comment by aamirki** [comment]
Any updates on this?
